trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: 'my-vsts-feed' # A series of numbers and letters

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'
- task: DownloadPackage@1
  inputs:
    packageType: 'nuget'
    feed: '/4522db04-941a-408b-8fb4-453f512b8114'
    view: '39e5bf0a-0728-4189-95f2-3abb58db93ba'
    definition: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)'